-- Table used to store debug logs generated during execution
CREATE TABLE DEBUG_LOG (
  LOG_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  LOG_TIME TIMESTAMP DEFAULT SYSTIMESTAMP,
  MODULE_NAME VARCHAR2(100),
  LINE_NO NUMBER,
  LOG_MESSAGE VARCHAR2(4000),
  SESSION_ID VARCHAR2(50) DEFAULT SYS_CONTEXT('USERENV','SESSIONID')
);

-- Create a working copy of the EMPLOYEES table
-- This is used to avoid modifying the original HR schema data
-- All salary adjustments will be performed on this copy
CREATE TABLE EMPLOYEES_COPY AS
SELECT *
FROM HR.EMPLOYEES;